In [1]:
from IPython.core.debugger import set_trace
import numpy as np
import sys
import collections
import re
f=open('day21input.txt') #not with read because thats probably the whole file
lines = [line.rstrip('\n') for line in f]

In [2]:
print (lines[0:4])

['seti 123 0 5', 'bani 5 456 5', 'eqri 5 72 5', 'addr 5 4 4']


In [55]:

def addr(reg,ins): #
    #(add register) stores into register C the result of adding register A and register B.
    result = reg[ins[1]]+reg[ins[2]]
    reg[ins[3]]=result
    return reg

def addi(reg,ins):#
    #addi (add immediate) stores into register C the result of adding register A and value B.

    reg[ins[3]]=reg[ins[1]]+ins[2]
    return reg


def mulr(reg,ins):#
    #mulr (multiply register) stores into register C the result of multiplying register A and register B.
    #set_trace()
    reg[ins[3]]=reg[ins[1]]*reg[ins[2]]
    return reg


def muli(reg,ins):#
    #muli (multiply immediate) stores into register C the result of multiplying register A and value B.
 
    reg[ins[3]]=reg[ins[1]]*ins[2]
    return reg



def banr(reg,ins):#
    #banr (bitwise AND register) stores into register C the result of the bitwise AND of register A and register B.

    reg[ins[3]]=int(reg[ins[1]])&int(reg[ins[2]])
    return reg



def bani(reg,ins):#
    #bani (bitwise AND immediate) stores into register C the result of the bitwise AND of register A and value B.
 
    reg[ins[3]]=int(reg[ins[1]])&int(ins[2])
    return reg



def borr(reg,ins):#
    #borr (bitwise OR register) stores into register C the result of the bitwise OR of register A and register B.

    reg[ins[3]]=int(reg[ins[1]])|int(reg[ins[2]])
    return reg



def bori(reg,ins):#
    #bori (bitwise OR immediate) stores into register C the result of the bitwise OR of register A and value B.
  
    reg[ins[3]]=int(reg[ins[1]])|int(ins[2])

    return reg



def setr(reg,ins):#
    #setr (set register) copies the contents of register A into register C. (Input B is ignored.)
    
    reg[ins[3]]=reg[ins[1]]
    return reg


def seti(reg,ins):#
    #seti (set immediate) stores value A into register C. (Input B is ignored.)
  
    reg[ins[3]]=ins[1]
    return reg



def gtir(reg,ins):#
    #gtir (greater-than immediate/register) sets register C to 1 if value A is greater than register B. Otherwise, register C is set to 0.
    if ins[1]>reg[ins[2]]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg



def gtri(reg,ins):#
    #gtri (greater-than register/immediate) sets register C to 1 if register A is greater than value B. Otherwise, register C is set to 0.
    if reg[ins[1]]>ins[2]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg





def gtrr(reg,ins):#
    #gtrr (greater-than register/register) sets register C to 1 if register A is greater than register B. Otherwise, register C is set to 0.
    if reg[ins[1]]>reg[ins[2]]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg




def eqir(reg,ins):#
    #eqir (equal immediate/register) sets register C to 1 if value A is equal to register B. Otherwise, register C is set to 0.

    if ins[1]==reg[ins[2]]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg




def eqri(reg,ins):#
    #qri (equal register/immediate) sets register C to 1 if register A is equal to value B. Otherwise, register C is set to 0.

    if reg[ins[1]]==ins[2]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg




def eqrr(reg,ins):
    #eqrr (equal register/register) sets register C to 1 if register A is equal to register B. Otherwise, register C is set to 0.
    if reg[ins[1]]==reg[ins[2]]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg



In [97]:

instructions=[]
functions =[]
for i,line in enumerate(lines):
    newline =[0]
    for j,x in enumerate(line.split(' ')):
        #print (j,x)
        if j>0:
            newline.append(int(x))
        else:
            functions.append(x)
    instructions.append (newline)
instructions = np.array(instructions)


In [179]:
ip = 4
before = np.zeros(shape=6)
before = before.astype(np.int64)
before[ip]+=-1
#before=np.array([       0,      126,    65537,    65536,       19, 10285204])
before = before.astype(np.int64)
results = []

addvalue=[]

for i in range(100000000):
    
    before[ip]+=1
    if before[ip]>=len(instructions):
        print (before)
        sys.exit(0)
    elif before[ip]==28 :
        results.append(before)
        print (before)
    if before[ip] in [28]: 
        print (before[ip], functions[before[ip]],instructions[before[ip]][1:],before)#,before,eval(functions[before[ip]])(before.copy(),instructions[before[ip]]))
    #if before[ip] in [9]:
    #    addvalue.append([before[1]])
    #    print (before[1])
    before = eval(functions[before[ip]])(before.copy(),instructions[before[ip]])

[      0       1       1       1      28 2884703]
28 eqrr [5 0 1] [      0       1       1       1      28 2884703]
[      0       1       1      45      28 8786036]
28 eqrr [5 0 1] [      0       1       1      45      28 8786036]
[      0       1       1     135      28 6734733]
28 eqrr [5 0 1] [      0       1       1     135      28 6734733]
[       0        1        1      103       28 13238691]
28 eqrr [5 0 1] [       0        1        1      103       28 13238691]
[       0        1        1      203       28 15167071]
28 eqrr [5 0 1] [       0        1        1      203       28 15167071]


KeyboardInterrupt: 

In [ ]:
7 seti [733884      6      5] [      0       0       1 2950239       7 2884703]
9 addr [5 1 5] [      0      95       1 2950239       9  733884]
10 bani [       5 16777215        5] [      0      95       1 2950239      10  733979]
11 muli [    5 65899     5] [      0      95       1 2950239      11  733979]
12 bani [       5 16777215        5] [          0          95           1     2950239          12 48368482121]
9 addr [5 1 5] [       0        4        1    11524        9 16545609]
10 bani [       5 16777215        5] [       0        4        1    11524       10 16545613]
11 muli [    5 65899     5] [       0        4        1    11524       11 16545613]
12 bani [       5 16777215        5] [            0             4             1         11524            12
 1090339351087]
9 addr [5 1 5] [      0      45       1      45       9 4860463]
10 bani [       5 16777215        5] [      0      45       1      45      10 4860508]
11 muli [    5 65899     5] [      0      45       1      45      11 4860508]
12 bani [       5 16777215        5] [           0           45            1           45           12
 320302616692]
[      0       1       1      45      28 8786036]

In [171]:
i

320302616692

In [172]:
320302616692&16777215

8786036

In [189]:
#puzzle 2
oldvalues =[]
    
start = 733884
oldvalue = 2884703
oldvalues =[oldvalue]
for x in range(12000):
    if x%10000==0: print (x)
    add1 = (oldvalue|65536)&255
    b = start + add1
    c = 65899*(b&16777215)
    d = c&16777215
    #print (d)
    add2 = ((oldvalue|65536)//256)&255
    e = d+add2
    f = 65899*(e&16777215)
    g = f&16777215
    #print (g)
    add3 = (((oldvalue|65536)//256)//256)&255
    h = g+add3
    i = 65899*(h&16777215)
    j = i&16777215
    print (j)
    oldvalue = j
    if oldvalue in oldvalues:
        print ('OLDVALUE',x, oldvalue)
        #sys.exit()
    else: oldvalues.append(oldvalue)

0
8786036
6734733
13238691
15167071
11679948
16722785
4939023
3691359
3864719
6294578
10466657
6048937
14600330
7087215
1345412
11217686
9066914
14886628
7595575
12348944
524193
7033691
5885481
1964880
9941350
820236
13881515
12619750
16026760
14149535
15892557
9895164
3041505
6358452
3114104
193509
9548559
1024199
200798
7805247
15542319
12464936
11930012
7430534
65210
445499
7536494
14682102
10554576
14682971
1028467
12776299
115649
6304221
1525135
3273163
9539177
9220408
2285300
4362271
8820754
4972047
1159832
5296377
12122330
4934445
10089495
1523632
12732456
7489653
9968636
5637918
16540442
3200940
694674
1399412
6613857
11701617
16630093
7978019
15781308
11097032
11138410
9619458
9088147
10690562
14219739
4741017
12911857
14978898
4808600
8404582
15543231
141827
11341448
4074105
2552286
14932580
15181515
16761928
15432069
11997373
16374600
5091234
3520800
1429548
9975119
16607697
12216151
7800001
11325736
16096836
12423829
15653060
1462653
16422049
1542660
13044887
15807170
16570

In [103]:
7 seti [733884      6      5] [      0       0       1 2950239       7 2884703]
9 addr [5 1 5] [      0      95       1 2950239       9  733884]
12 bani [       5 16777215        5] [          0          95           1     2950239          12 48368482121]
13 gtir [256   3   1] [       0       95        1  2950239       13 16545609]
9 addr [5 1 5] [       0        4        1    11524        9 16545609]
12 bani [       5 16777215        5] [            0             4             1         11524            12
 1090339351087]
13 gtir [256   3   1] [      0       4       1   11524      13 4860463]
9 addr [5 1 5] [      0      45       1      45       9 4860463]
12 bani [       5 16777215        5] [           0           45            1           45           12
 320302616692]
13 gtir [256   3   1] [      0      45       1      45      13 8786036]
[      0       1       1      45      28 8786036]
28 eqrr [5 0 1] [      0       1       1      45      28 8786036]  

2950239

In [120]:
print (addvalue)

[[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]]


In [38]:
2884703
seti 733884
muli en bani 13185717
16770727
8589005
10681519
13323301
6944887
12210365
15563775
12440213
12491079
9066413
14111311
10532357
15145239

for j in range(1):
    result =[]   
    beforelist=[]
    ip = 4
    before = np.zeros(shape=6)
    before = before.astype(np.int64)
    before[ip]+=-1
    for i in range(1000):

        before[ip]+=1
        if before[ip]>=len(instructions):
            print (before)
            sys.exit(0)
        else:  
            result.append(before[ip])
            beforelist.append(before)
            before = eval(functions[before[ip]])(before.copy(),instructions[before[ip]])
    print (j,'\t',beforelist[900:920])

0 	 [array([       0,      126,    32512,    65536,       20, 10285204], dtype=int64), array([       0,      126,        0,    65536,       21, 10285204], dtype=int64), array([       0,      126,        0,    65536,       22, 10285204], dtype=int64), array([       0,      126,        0,    65536,       24, 10285204], dtype=int64), array([       0,      127,        0,    65536,       25, 10285204], dtype=int64), array([       0,      127,        0,    65536,       18, 10285204], dtype=int64), array([       0,      127,      128,    65536,       19, 10285204], dtype=int64), array([       0,      127,    32768,    65536,       20, 10285204], dtype=int64), array([       0,      127,        0,    65536,       21, 10285204], dtype=int64), array([       0,      127,        0,    65536,       22, 10285204], dtype=int64), array([       0,      127,        0,    65536,       24, 10285204], dtype=int64), array([       0,      128,        0,    65536,       25, 10285204], dtype=int64), array([    

In [39]:
for i in range(900,920):
    print(functions[result[i]],instructions[result[i]][1:],beforelist[i])

gtrr [2 3 2] [       0      126    32512    65536       20 10285204]
addr [2 4 4] [       0      126        0    65536       21 10285204]
addi [4 1 4] [       0      126        0    65536       22 10285204]
addi [1 1 1] [       0      126        0    65536       24 10285204]
seti [17  8  4] [       0      127        0    65536       25 10285204]
addi [1 1 2] [       0      127        0    65536       18 10285204]
muli [  2 256   2] [       0      127      128    65536       19 10285204]
gtrr [2 3 2] [       0      127    32768    65536       20 10285204]
addr [2 4 4] [       0      127        0    65536       21 10285204]
addi [4 1 4] [       0      127        0    65536       22 10285204]
addi [1 1 1] [       0      127        0    65536       24 10285204]
seti [17  8  4] [       0      128        0    65536       25 10285204]
addi [1 1 2] [       0      128        0    65536       18 10285204]
muli [  2 256   2] [       0      128      129    65536       19 10285204]
gtrr [2 3 2] [  

In [ ]:
10285204 too high
10212486
2884703 correct
10312233 too low
16743306 too high
16722785 too high

In [62]:
print (bin(2884703)[2:])  
print (bin(8786036)[2:])  
print (bin(6734733)[2:]) 
print (bin(13238691)[2:])  
print (bin(15167071)[2:])  
print (bin(11679948)[2:])  

print (bin(11217686)[2:])  


1011000000010001011111
100001100001000001110100
11001101100001110001101
110010100000000110100011
111001110110111001011111
101100100011100011001100
101010110010101100010110


In [71]:
print (bin(65536)[2:])  
print (bin(255)[2:])  
print (bin(16777215)[2:])  
print (bin(733884+255)[2:])
print (16777215&(733884+255)*65899)
print (10312233&16777215)

10000000000000000
11111111
111111111111111111111111
10110011001110111011
10312233
10312233


In [70]:
print(65536|65536)

65536


In [ ]:
bori 5 65536 3   bitwise or reg5 5 value 65536 store in 3
seti 733884 6 5  reg 5= 733884
bani 3 255 1     bitwise and reg 3 and 255 set in 1
addr 5 1 5       add reg 1 to reg 5 --> reg 5 = 733884+(max 255)
bani 5 16777215 5bitwise and reg 5 and 16777215
muli 5 65899 5  multiply 65899 and reg 5
bani 5 16777215 5bitwise and 16777215(111111111111111111111111)

In [ ]:
seti 123 0 5
bani 5 456 5
eqri 5 72 5
addr 5 4 4
seti 0 0 4
seti 0 7 5
bori 5 65536 3
seti 733884 6 5
bani 3 255 1
addr 5 1 5
bani 5 16777215 5
muli 5 65899 5
bani 5 16777215 5
gtir 256 3 1
addr 1 4 4
addi 4 1 4
seti 27 8 4
seti 0 6 1
addi 1 1 2
muli 2 256 2
gtrr 2 3 2
addr 2 4 4
addi 4 1 4
seti 25 4 4
addi 1 1 1
seti 17 8 4
setr 1 7 3
seti 7 0 4
eqrr 5 0 1
addr 1 4 4
seti 5 9 4

In [90]:
inputvalue= 733884
for x in range(15):
    print ((inputvalue*65899)&16777215)
    inputvalue = (inputvalue*65899)&16777215

10285204
1909212
2818804
15806460
16452180
4957468
6233780
9734460
14325780
631900
527988
14712444
13588948
14180252
7049780


In [76]:
end=[]
for i in range(256):

    a = 733884+i
    b = a & 16777215
    c= 65899* b
    d = 16777215 & c
    print (i, d)
    end.append(d)
print (max(end))

0 10285204
1 10351103
2 10417002
3 10482901
4 10548800
5 10614699
6 10680598
7 10746497
8 10812396
9 10878295
10 10944194
11 11010093
12 11075992
13 11141891
14 11207790
15 11273689
16 11339588
17 11405487
18 11471386
19 11537285
20 11603184
21 11669083
22 11734982
23 11800881
24 11866780
25 11932679
26 11998578
27 12064477
28 12130376
29 12196275
30 12262174
31 12328073
32 12393972
33 12459871
34 12525770
35 12591669
36 12657568
37 12723467
38 12789366
39 12855265
40 12921164
41 12987063
42 13052962
43 13118861
44 13184760
45 13250659
46 13316558
47 13382457
48 13448356
49 13514255
50 13580154
51 13646053
52 13711952
53 13777851
54 13843750
55 13909649
56 13975548
57 14041447
58 14107346
59 14173245
60 14239144
61 14305043
62 14370942
63 14436841
64 14502740
65 14568639
66 14634538
67 14700437
68 14766336
69 14832235
70 14898134
71 14964033
72 15029932
73 15095831
74 15161730
75 15227629
76 15293528
77 15359427
78 15425326
79 15491225
80 15557124
81 15623023
82 15688922
83 15754821
84

In [80]:
end=[]
for i in range(10000):
    a = i|65536
    b = a&255
    print (i,b)
    end.append(b)
print (end)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11
12 12
13 13
14 14
15 15
16 16
17 17
18 18
19 19
20 20
21 21
22 22
23 23
24 24
25 25
26 26
27 27
28 28
29 29
30 30
31 31
32 32
33 33
34 34
35 35
36 36
37 37
38 38
39 39
40 40
41 41
42 42
43 43
44 44
45 45
46 46
47 47
48 48
49 49
50 50
51 51
52 52
53 53
54 54
55 55
56 56
57 57
58 58
59 59
60 60
61 61
62 62
63 63
64 64
65 65
66 66
67 67
68 68
69 69
70 70
71 71
72 72
73 73
74 74
75 75
76 76
77 77
78 78
79 79
80 80
81 81
82 82
83 83
84 84
85 85
86 86
87 87
88 88
89 89
90 90
91 91
92 92
93 93
94 94
95 95
96 96
97 97
98 98
99 99
100 100
101 101
102 102
103 103
104 104
105 105
106 106
107 107
108 108
109 109
110 110
111 111
112 112
113 113
114 114
115 115
116 116
117 117
118 118
119 119
120 120
121 121
122 122
123 123
124 124
125 125
126 126
127 127
128 128
129 129
130 130
131 131
132 132
133 133
134 134
135 135
136 136
137 137
138 138
139 139
140 140
141 141
142 142
143 143
144 144
145 145
146 146
147 147
148 148
149 149
150 150
151 151
152 

In [122]:
addvalue

[[0],
 [0],
 [1],
 [95],
 [4],
 [45],
 [116],
 [16],
 [135],
 [141],
 [195],
 [103],
 [163],
 [1],
 [203],
 [95],
 [110],
 [231],
 [204],
 [56],
 [179],
 [97],
 [43],
 [255],
 [15],
 [93],
 [75],
 [95],
 [83],
 [57],
 [143],
 [248],
 [59],
 [50],
 [12],
 [97],
 [97],
 [181],
 [159],
 [169],
 [76],
 [93],
 [138],
 [200],
 [223],
 [111],
 [36],
 [109],
 [132],
 [135],
 [21],
 [22],
 [43],
 [171],
 [162],
 [89],
 [139],
 [228],
 [38],
 [227],
 [55],
 [230],
 [115],
 [16],
 [110],
 [189],
 [161],
 [255],
 [7],
 [91],
 [83],
 [107],
 [41],
 [206],
 [89],
 [80],
 [251],
 [29],
 [102],
 [177],
 [151],
 [12],
 [132],
 [13],
 [171],
 [208],
 [211],
 [230],
 [143],
 [193],
 [136],
 [140],
 [245],
 [159],
 [231],
 [215],
 [77],
 [128],
 [243],
 [252],
 [252],
 [151],
 [225],
 [104],
 [47],
 [180],
 [5],
 [97],
 [120],
 [132],
 [47],
 [229],
 [243],
 [3],
 [15],
 [179],
 [145],
 [199],
 [160],
 [15],
 [94],
 [16],
 [3],
 [63],
 [25],
 [119],
 [47],
 [40],
 [237],
 [40],
 [51],
 [191],
 [156],
 [9]

In [125]:
add1 = [x for i,x in enumerate(addvalue) if i%3==0] 
add2 = [x for i,x in enumerate(addvalue) if i%3==1] 
add3 =[x for i,x in enumerate(addvalue) if i%3==2] 

In [126]:
print (add1)
print (add2)
print (add3)

[[0], [95], [116], [141], [163], [95], [204], [97], [15], [95], [143], [50], [97], [169], [138], [111], [132], [22], [162], [228], [55], [16], [161], [91], [41], [80], [102], [12], [171], [230], [136], [159], [77], [252], [225], [180], [120], [229], [15], [199], [94], [63], [47], [40], [156], [134], [186], [59], [110], [246], [208], [91], [115], [107], [193], [221], [143], [203], [105], [56], [244], [31], [18]]
[[0], [4], [16], [195], [1], [110], [56], [43], [93], [83], [248], [12], [181], [76], [200], [36], [135], [43], [89], [38], [230], [110], [255], [83], [206], [251], [177], [132], [208], [143], [140], [231], [128], [252], [104], [5], [132], [243], [179], [160], [16], [25], [40], [51], [9], [97], [254], [204], [255], [7], [12], [11], [177], [243], [195], [49], [69], [241], [142], [177], [222], [144]]
[[1], [45], [135], [103], [203], [231], [179], [255], [75], [57], [59], [97], [159], [93], [223], [109], [21], [171], [139], [227], [115], [189], [7], [107], [89], [29], [151], [13], 

In [129]:
65536   /256

256.0

In [3]:
import numpy as np
a = np.array([[10000000,1,2,3,4,5,6,7,8,9],[10000000,1,2,3,4,5,6,7,8,1000000]])
import pandas as pd


In [5]:
pd.DataFrame(a)

0  1  2  3  4  5  6  7  8        9
0  10000000  1  2  3  4  5  6  7  8        9
1  10000000  1  2  3  4  5  6  7  8  1000000

In [6]:
print(np.matrix(a))

[[10000000        1        2        3        4        5        6        7
         8        9]
 [10000000        1        2        3        4        5        6        7
         8  1000000]]


In [7]:
print('\n'.join(['\t'.join([str(cell) for cell in row]) for row in a]))

10000000	1	2	3	4	5	6	7	8	9
10000000	1	2	3	4	5	6	7	8	1000000


In [12]:
import pprint
pp = pprint.PrettyPrinter(indent=1)
pp.pprint(a)

array([[10000000,        1,        2,        3,        4,        5,
               6,        7,        8,        9],
       [10000000,        1,        2,        3,        4,        5,
               6,        7,        8,  1000000]])


In [14]:
a={'a':21343124324132,'adsjj':21343124324132,'assdfds':21343124324132,'eeeee':21343124324132,'e':21343124324132}
import json
json.dumps(a, indent=4)

'{\n    "a": 21343124324132,\n    "adsjj": 21343124324132,\n    "assdfds": 21343124324132,\n    "eeeee": 21343124324132,\n    "e": 21343124324132\n}'

In [15]:
pp.pprint(a)

{'a': 21343124324132,
 'adsjj': 21343124324132,
 'assdfds': 21343124324132,
 'e': 21343124324132,
 'eeeee': 21343124324132}
