In [18]:
import numpy as np
import collections
import networkx as nx

In [19]:
#target = (10,10)
#depth = 510

target = (721,7)
depth = 9171
caveshape = (1500,70)

xmultiply= 48271
ymultiply = 16807
m = 20183
endm = 3

cave = np.zeros(shape=caveshape)
erosion = np.zeros(shape=cave.shape)
geology = np.zeros(shape=cave.shape)

cave.astype(np.int64)
for y in range(cave.shape[1]): #geology index colums
    cave[0,y]=(ymultiply*y)%m
    erosion[0,y]=((cave[0,y]+depth)%m)
for x in range(cave.shape[0]):#geology index rows
    cave[x,0]=(xmultiply*x)%m
    erosion[x,0]=((cave[x,0]+depth)%m)

for x in range(1,cave.shape[0]): #geology index rest
    for y in range(1,cave.shape[1]):
        if x==target[0] and y==target[1]:
            cave[target]=0
            erosion[target]=depth%m
        else:
            cave[x,y]=(erosion[x-1,y]*erosion[x,y-1])%m
            erosion[x,y]=((cave[x,y]+depth)%m)
        
for i, cell in np.ndenumerate(geology):
    geology[i]=erosion[i]%endm
    

In [20]:
cave

array([[     0.,  16807.,  13431., ...,  16004.,  12628.,   9252.],
       [  7905.,  18354.,  19441., ...,  11320.,  13336.,   6909.],
       [ 15810.,   7581.,   2340., ...,  19671.,   1065.,   2515.],
       ..., 
       [  6547.,  11826.,  15510., ...,  13718.,  15223.,  17699.],
       [ 14452.,  14906.,  16551., ...,  11470.,  11253.,  17110.],
       [  2174.,  17026.,   9596., ...,  12781.,   2486.,  20043.]])

In [21]:
erosion

array([[  9171.,   5795.,   2419., ...,   4992.,   1616.,  18423.],
       [ 17076.,   7342.,   8429., ...,    308.,   2324.,  16080.],
       [  4798.,  16752.,  11511., ...,   8659.,  10236.,  11686.],
       ..., 
       [ 15718.,    814.,   4498., ...,   2706.,   4211.,   6687.],
       [  3440.,   3894.,   5539., ...,    458.,    241.,   6098.],
       [ 11345.,   6014.,  18767., ...,   1769.,  11657.,   9031.]])

In [22]:
geology

array([[ 0.,  2.,  1., ...,  0.,  2.,  0.],
       [ 0.,  1.,  2., ...,  2.,  2.,  0.],
       [ 1.,  0.,  0., ...,  1.,  0.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  0.,  2.,  0.],
       [ 2.,  0.,  1., ...,  2.,  1.,  2.],
       [ 2.,  2.,  2., ...,  2.,  2.,  1.]])

In [23]:
np.sum(geology[0:target[0]+1,0:target[1]+1])

5786.0

In [24]:
neighborarray = np.array([(0,1),(1,0)])

def getneighbors(cell):
    neighbors = cell+neighborarray
    return [tuple(x) for x in neighbors if (x[0]>=0 and x[1]>=0 and x[0]<geology.shape[0] and x[1]<geology.shape[1])]


gear={0:['t','c'],
     1:['c','n'],
     2:['t','n']}
edges = []
for i, cell in np.ndenumerate(geology):
    node1 = (i,gear[cell][0])
    node2 = (i,gear[cell][1])
    neighbors=getneighbors(i)
    
    for owngear in gear[geology[i]]:
        for n in neighbors:
            for neighborgear in gear[geology[n]]:
                if owngear == neighborgear:
                    weight = 1
                #else:
                #    weight = 8
                    edges.append(((i,owngear),(n,neighborgear),weight))
                #print (edges[-1])
    edges.append((node1,node2,7))
    #print (edges[-1])

#puzzle2

G=nx.Graph()
#G.add_nodes_from(nodes)
G.add_weighted_edges_from(edges)


In [25]:
nx.algorithms.shortest_paths.weighted.dijkstra_path_length(G,((0, 0), 't'),(target, 't'),weight='weight')

986

In [26]:
nx.algorithms.shortest_paths.weighted.dijkstra_path(G,((0, 0), 't'),(target, 't'),weight='weight')

[((0, 0), 't'),
 ((0, 1), 't'),
 ((0, 1), 'n'),
 ((0, 2), 'n'),
 ((0, 3), 'n'),
 ((0, 4), 'n'),
 ((1, 4), 'n'),
 ((1, 5), 'n'),
 ((2, 5), 'n'),
 ((3, 5), 'n'),
 ((4, 5), 'n'),
 ((5, 5), 'n'),
 ((5, 4), 'n'),
 ((6, 4), 'n'),
 ((7, 4), 'n'),
 ((8, 4), 'n'),
 ((9, 4), 'n'),
 ((10, 4), 'n'),
 ((10, 5), 'n'),
 ((11, 5), 'n'),
 ((11, 6), 'n'),
 ((11, 7), 'n'),
 ((12, 7), 'n'),
 ((13, 7), 'n'),
 ((14, 7), 'n'),
 ((15, 7), 'n'),
 ((15, 6), 'n'),
 ((15, 5), 'n'),
 ((15, 4), 'n'),
 ((16, 4), 'n'),
 ((17, 4), 'n'),
 ((18, 4), 'n'),
 ((19, 4), 'n'),
 ((20, 4), 'n'),
 ((20, 3), 'n'),
 ((20, 2), 'n'),
 ((21, 2), 'n'),
 ((22, 2), 'n'),
 ((23, 2), 'n'),
 ((24, 2), 'n'),
 ((25, 2), 'n'),
 ((26, 2), 'n'),
 ((26, 3), 'n'),
 ((26, 4), 'n'),
 ((27, 4), 'n'),
 ((28, 4), 'n'),
 ((29, 4), 'n'),
 ((30, 4), 'n'),
 ((31, 4), 'n'),
 ((31, 5), 'n'),
 ((32, 5), 'n'),
 ((32, 6), 'n'),
 ((33, 6), 'n'),
 ((34, 6), 'n'),
 ((35, 6), 'n'),
 ((36, 6), 'n'),
 ((37, 6), 'n'),
 ((37, 6), 't'),
 ((38, 6), 't'),
 ((38, 7), 't'