In [ ]:
from IPython.core.debugger import set_trace
import numpy as np
import sys
import collections
import re
from pprint import pprint
import networkx as nx

In [67]:
f=open('day25input.txt') #not with read because thats probably the whole file
lines = [line.rstrip('\n') for line in f]

In [68]:
stars=[]

for line in lines:
    star=[]
    for item in line.split(','):
        star.append(int(item))
    stars.append(star)

In [69]:
stars=np.array(stars)

In [70]:
def getmanhattan(a,b):
    return abs(a[0]-b[0])+abs(a[1]-b[1])+abs(a[2]-b[2])+abs(a[3]-b[3])

In [71]:
num_stars = stars.shape[0]
edges =[]
max_distance = 3
nodes=[]
for x in range(num_stars):
    for y in range(num_stars):
        if y<x:
            if getmanhattan(stars[x],stars[y]) <= max_distance:
                edges.append((x,y))
                print (stars[x],stars[y],distance)
for x in range (num_stars):
    nodes.append(x)

[ 7  0 -8 -4] [ 8  0 -8 -4] 3
[ 1  3  8 -5] [ 3  3  8 -5] 3
[ 0 -3  8 -6] [ 0 -3  5 -6] 3
[-3  6 -3  5] [-3  5 -5  5] 3
[ 3  1 -3  3] [ 2  1 -2  4] 3
[-1  8 -1  1] [-3  8 -1  2] 3
[-5 -1 -6 -6] [-4  0 -6 -5] 3
[ 7  0 -3  7] [ 7 -2 -3  8] 3
[ 1  3  6 -5] [ 1  3  8 -5] 3
[-8 -5 -6  8] [-8 -5 -8  8] 3
[ 7 -2 -8  6] [ 8 -2 -8  8] 3
[-1 -4 -1  1] [ 0 -4  0  0] 3
[-2  5 -8 -6] [-2  7 -7 -6] 3
[ 1  2  5 -3] [-1  2  4 -3] 3
[ 8  1 -8 -3] [ 8  0 -8 -4] 3
[ 8  1 -8 -3] [ 7  0 -8 -4] 3
[ 2 -1  2  6] [2 0 3 5] 3
[ 0  0 -2  1] [ 0  0 -3  1] 3
[-6  1  0  2] [-5  1  0  3] 3
[ 6 -5 -2  1] [ 7 -5 -1  1] 3
[ 3  1 -1  2] [ 3  1 -3  3] 3
[2 3 2 6] [2 2 1 7] 3
[-1 -2 -7  7] [-1 -3 -6  8] 3
[-1  4  4  7] [-1  3  6  7] 3
[-1  4  4  7] [0 4 4 7] 3
[-5 -2 -7 -4] [-6 -2 -7 -5] 3
[ 3  8  0 -5] [ 3  8  1 -5] 3
[3 6 1 4] [2 8 1 4] 3
[ 2  0  1 -6] [ 2 -1  0 -5] 3
[ 2  0  1 -6] [ 1  0  1 -7] 3
[ 7 -5 -8  8] [ 5 -5 -8  8] 3
[ 0 -4  0  7] [ 1 -6  0  7] 3
[ 0 -3  1 -5] [ 1 -3  2 -4] 3
[ 0  7 -1 -6] [ 1  7 -1 -7] 3
[ 8 

In [72]:
G=nx.Graph()
#G.add_nodes_from(nodes)
G.add_edges_from(edges)
G.add_nodes_from(nodes)
a =[G.subgraph(c) for c in nx.connected_components(G)]

In [73]:
len(a)

428

In [ ]:
159 too low

In [68]:
def removebots(removelist):
    global bots
    for i in reversed(removelist):
        bots = np.delete(bots, i, 0)
        power = np.delete(power, i, 0)

def interpretresults (result,shrink):
    focusindices=[]
    for i,val in np.ndenumerate(result):
        if val>800:
            focusindices.append(i,val)
    focusindices.sort(key=lambda x: x[1])
    print (focusindices)

In [41]:
shrink = 10000000
mininput = [0,0,0]
maxinput = [39, 23, 35]
result7,removelist7,minres,maxres = calc_lights(shrink,mininput,maxinput)
#minres & maxres [17, 10, 16] [22, 15, 21] range (40, 24, 36)

new focus values, where we are in new grid [0, 0, 0] [39, 23, 35]
the ranges for x y z. this defines the shape of new array [39, 23, 35]
signal shape should be equal to maxres + 1 (40, 24, 36)
botnr 0 botlocation (17, 11, 17) botpower 7
botnr 100 botlocation (16, 11, 18) botpower 8
botnr 200 botlocation (28, 13, 18) botpower 10
botnr 300 botlocation (19, 12, 21) botpower 7
botnr 400 botlocation (15, 15, 20) botpower 10
botnr 500 botlocation (20, 11, 26) botpower 11
botnr 600 botlocation (18, 12, 24) botpower 9
botnr 700 botlocation (24, 13, 20) botpower 7
botnr 800 botlocation (22, 12, 18) botpower 11
botnr 900 botlocation (17, 12, 15) botpower 8
botsalwayslight 0 
 botsalwaysdark 0
[[20, 13, 18, 985.0],
 [19, 13, 18, 982.0],
 [20, 13, 19, 979.0],
 [19, 13, 19, 977.0],
 [20, 12, 18, 973.0],
 [19, 12, 19, 968.0],
 [19, 12, 18, 966.0],
 [20, 12, 19, 962.0],
 [19, 14, 19, 936.0],
 [18, 12, 19, 934.0],
 [18, 13, 19, 934.0],
 [19, 13, 20, 933.0],
 [19, 12, 20, 923.0],
 [19, 11, 19, 917.0],


In [44]:
#this is new mininput [170, 100, 160]
#this is new maxinput [220, 150, 210]
shrink = 1000000
result6,removelist6,minres,maxres = calc_lights(shrink,mininput,maxinput)
#botsalwayslight 22 
# botsalwaysdark 15
#minres & maxres [28, 30, 25] [34, 35, 30] range (51, 51, 51)

new focus values, where we are in new grid [170, 100, 160] [220, 150, 210]
the ranges for x y z. this defines the shape of new array [50, 50, 50]
signal shape should be equal to maxres + 1 (51, 51, 51)
botnr 0 botlocation (173, 117, 179) botpower 55
removebot always dark 34 (5, 127, 193) 60
removebot always light 34 (5, 127, 193) 60
removebot always light 35 (203, 118, 192) 97
removebot always light 94 (193, 119, 182) 93
removebot always dark 97 (389, 119, 195) 60
removebot always light 97 (389, 119, 195) 60
botnr 100 botlocation (160, 117, 181) botpower 65
removebot always dark 141 (330, 100, 245) 58
removebot always light 141 (330, 100, 245) 58
removebot always dark 164 (207, 0, 257) 97
removebot always light 164 (207, 0, 257) 97
removebot always dark 171 (200, 73, 334) 91
removebot always light 171 (200, 73, 334) 91
botnr 200 botlocation (281, 137, 189) botpower 88
removebot always light 213 (197, 126, 197) 90
removebot always dark 219 (193, 120, 0) 92
removebot always light 219 (19

In [48]:
#this is new mininput [1980, 1300, 1850]
#this is new maxinput [2040, 1350, 1900]
mininput =[1990, 1310, 1850]
maxinput = [2040, 1350, 1900]
shrink = 100000
result5,removelist5,minres,maxres = calc_lights(shrink,mininput,maxinput)
#botsalwayslight 60 
# botsalwaysdark 15
#minres & maxres [31, 17, 15] [35, 31, 29] range (51, 41, 51)

new focus values, where we are in new grid [1990, 1310, 1850] [2040, 1350, 1900]
the ranges for x y z. this defines the shape of new array [50, 40, 50]
signal shape should be equal to maxres + 1 (51, 41, 51)
botnr 0 botlocation (1735, 1171, 1792) botpower 533
always dark False always light True 23 (1923, 1305, 1878) 586
always dark True always light True 34 (55, 1270, 1936) 589
always dark False always light True 35 (2035, 1184, 1920) 961
always dark False always light True 85 (2206, 1254, 1912) 566
always dark False always light True 94 (1931, 1197, 1826) 920
always dark True always light True 97 (3890, 1199, 1958) 588
botnr 100 botlocation (1604, 1179, 1812) botpower 635
always dark False always light True 103 (2088, 1525, 1950) 935
always dark False always light True 107 (1950, 1237, 1909) 665
always dark False always light True 119 (1965, 1298, 1809) 649
always dark True always light True 141 (3305, 1000, 2459) 571
always dark True always light True 164 (2072, 0, 2576) 956
always d

In [70]:
#this is new mininput [20210, 13270, 18650]
#this is new maxinput [20250, 13410, 18790]
mininput =[20210, 13370, 18650]
maxinput =[20250, 13410, 18700]
shrink = 10000
result4,removelist4,minres,maxres = calc_lights(shrink,mininput,maxinput)

#botsalwayslight 0 
#botsalwaysdark 0
#minres & maxres [25, 0, 22] [29, 29, 51] range (41, 41, 51)

new focus values, where we are in new grid [20210, 13370, 18650] [20250, 13410, 18700]
the ranges for x y z. this defines the shape of new array [40, 40, 50]
signal shape should be equal to maxres + 1 (41, 41, 51)
botnr 0 botlocation (17355, 11714, 17924) botpower 5317
botnr 100 botlocation (15494, 12643, 18785) botpower 5611
botnr 200 botlocation (15901, 11704, 19210) botpower 6567
botnr 300 botlocation (22880, 10290, 22164) botpower 9242
botnr 400 botlocation (14850, 12780, 21898) botpower 9230
botnr 500 botlocation (23705, 14829, 22001) botpower 8228
botnr 600 botlocation (25293, 11570, 19301) botpower 7512
botnr 700 botlocation (20397, 17903, 23754) botpower 9747
botnr 800 botlocation (22090, 8277, 18915) botpower 7216
botnr 900 botlocation (15911, 12640, 16789) botpower 6970
[[27, 27, 24, 925.0],
 [27, 28, 24, 924.0],
 [27, 27, 25, 923.0],
 [26, 27, 24, 917.0],
 [26, 27, 25, 913.0],
 [28, 27, 24, 913.0],
 [26, 26, 25, 908.0],
 [27, 27, 23, 907.0],
 [27, 26, 24, 906.0],
 [27, 26, 2

In [74]:
#mininput= [202350, 133700, 186720]
#maxinput= [202390, 133990, 187010]

#here i make the concious choice to focus on top side
#alternative to focus on (not yet explored) is
#mininput= [202350, 133700, 186960]
#maxinput= [202390, 133770, 187010]


mininput= [202350, 133940, 186720]
maxinput= [202390, 133990, 186770]
shrink = 1000
result3,removelist3,minres,maxres = calc_lights(shrink,mininput,maxinput)

new focus values, where we are in new grid [202350, 133940, 186720] [202390, 133990, 186770]
the ranges for x y z. this defines the shape of new array [40, 50, 50]
signal shape should be equal to maxres + 1 (41, 51, 51)
botnr 0 botlocation (173550, 117145, 179249) botpower 53156
botnr 100 botlocation (154940, 126433, 187854) botpower 56092
botnr 200 botlocation (159011, 117048, 192100) botpower 65651
botnr 300 botlocation (228800, 102901, 221648) botpower 92404
botnr 400 botlocation (148506, 127803, 218983) botpower 92284
botnr 500 botlocation (237059, 148290, 220012) botpower 82262
botnr 600 botlocation (252938, 115706, 193011) botpower 75101
botnr 700 botlocation (203973, 179036, 237548) botpower 97457
botnr 800 botlocation (220904, 82772, 189158) botpower 72147
botnr 900 botlocation (159111, 126409, 167894) botpower 69686
[[26, 38, 26, 902.0],
 [26, 38, 25, 900.0],
 [26, 37, 26, 882.0],
 [26, 14, 50, 880.0],
 [26, 15, 49, 880.0],
 [26, 16, 48, 880.0],
 [26, 17, 47, 880.0],
 [26, 18,

In [76]:
#mininput= [2023750, 1339520, 1867440]
#maxinput= [2023770, 1339790, 1867710]
mininput= [2023750, 1339750, 1867440]
maxinput= [2023770, 1339790, 1867480]

shrink = 100
result2,removelist2,minres,maxres = calc_lights(shrink,mininput,maxinput)

new focus values, where we are in new grid [2023750, 1339750, 1867440] [2023770, 1339790, 1867480]
the ranges for x y z. this defines the shape of new array [20, 40, 40]
signal shape should be equal to maxres + 1 (21, 41, 41)
botnr 0 botlocation (1735509, 1171451, 1792497) botpower 531556
botnr 100 botlocation (1549406, 1264330, 1878546) botpower 560913
botnr 200 botlocation (1590112, 1170482, 1921003) botpower 656509
botnr 300 botlocation (2288005, 1029016, 2216487) botpower 924039
botnr 400 botlocation (1485061, 1278037, 2189835) botpower 922839
botnr 500 botlocation (2370597, 1482908, 2200122) botpower 822616
botnr 600 botlocation (2529387, 1157060, 1930112) botpower 751002
botnr 700 botlocation (2039730, 1790363, 2375483) botpower 974566
botnr 800 botlocation (2209047, 827722, 1891580) botpower 721467
botnr 900 botlocation (1591111, 1264097, 1678949) botpower 696856
[[18, 36, 17, 919.0],
 [17, 36, 17, 906.0],
 [18, 36, 16, 905.0],
 [17, 36, 18, 900.0],
 [18, 35, 18, 900.0],
 [18, 3

In [78]:
#mininput= [20237660, 13397620, 18674550]
#maxinput= [20237690, 13397880, 18674810]
mininput= [20237660, 13397840, 18674560]
maxinput= [20237690, 13397870, 18674600]
shrink = 10
result1,removelist1,minres,maxres = calc_lights(shrink,mininput,maxinput)

new focus values, where we are in new grid [20237660, 13397840, 18674560] [20237690, 13397870, 18674600]
the ranges for x y z. this defines the shape of new array [30, 30, 40]
signal shape should be equal to maxres + 1 (31, 31, 41)
botnr 0 botlocation (17355091, 11714517, 17924976) botpower 5315553
always dark False always light True 3 (19142895, 12767957, 23040267) 6090423
always dark False always light True 21 (19403401, 18153982, 19346953) 6262835
always dark False always light True 22 (19233381, 8049484, 19253032) 6931181
always dark False always light True 29 (18324017, 11736108, 23408089) 8308977
always dark False always light True 32 (15412376, 9769072, 19616416) 9395972
always dark False always light True 36 (18561161, 8922378, 20104201) 7581676
always dark False always light True 51 (15355952, 11378790, 19280521) 7506785
always dark False always light True 57 (16389128, 11812645, 18825703) 5584944
always dark False always light True 70 (17043666, 8639749, 18009225) 8617541
alw

In [82]:
#minres & maxres [22, 23, 7] [27, 30, 14] range (31, 31, 41)
#mininput= [202376820, 133978630, 186745670]
#maxinput= [202376870, 133978700, 186745710]
mininput= [202376830, 133978660, 186745670]
maxinput= [202376870, 133978700, 186745740]
shrink = 1
result0,removelist0,minres,maxres = calc_lights(shrink,mininput,maxinput)


new focus values, where we are in new grid [202376830, 133978660, 186745670] [202376870, 133978700, 186745740]
the ranges for x y z. this defines the shape of new array [40, 40, 70]
signal shape should be equal to maxres + 1 (41, 41, 71)
botnr 0 botlocation (173550910, 117145172, 179249768) botpower 53155529
always dark False always light True 0 (173550910, 117145172, 179249768) 53155529
always dark False always light True 1 (199149199, 63786206, 206184804) 92859394
always dark False always light True 3 (191428951, 127679575, 230402670) 60904226
always dark False always light True 8 (176269313, 149063899, 199060171) 53507299
always dark False always light True 9 (179366302, 140414834, 217936656) 60637779
always dark False always light True 12 (144121227, 158792341, 190520563) 86844269
always dark False always light True 14 (154293513, 138583577, 192835519) 58778125
always dark False always light True 20 (163477594, 91740715, 181334940) 86548317
always dark False always light True 21 (1

In [80]:
print ('this was min input and min result',mininput,minres)
print ('this was max result',maxres)
tempmin=[]
tempmax=[]
for i in [0,1,2]:
    tempmin.append(10*mininput[i]+10*minres[i])
    tempmax.append(10*mininput[i]+10*maxres[i])
mininput = tempmin
maxinput = tempmax
print ('#mininput=',mininput)
print ('#maxinput=',maxinput)

this was min input and min result [20237660, 13397840, 18674560] [22, 23, 7]
this was max result [27, 30, 14]
#mininput= [202376820, 133978630, 186745670]
#maxinput= [202376870, 133978700, 186745740]


In [65]:
print (len(removelist5))
print (len(bots))
print (len(power))

75
925
1000


In [56]:
for i in removelist5[0:5]:
    print (i,bots[i])
    print (i,power[i])

23 [192326451 130557527 187868434]
23 58424444
34 [  5574728 127077686 193644312]
34 58709763
35 [203569388 118485428 192003350]
35 95918411
85 [220617154 125444664 191242332]
85 56413925
94 [193129155 119748703 182639171]
94 91848130
