In [67]:
from IPython.core.debugger import set_trace
import numpy as np
import sys
import collections
import re
f=open('day19input.txt') #not with read because thats probably the whole file
lines = [line.rstrip('\n') for line in f]

In [68]:
print (lines[0:4])

['addi 3 16 3', 'seti 1 8 5', 'seti 1 0 4', 'mulr 5 4 2']


In [69]:
15400012 seti [       0 10551343        0        2  1925000        1]seti 1 0 4     set ip to 2
15400013 mulr [       0 10551343  1925000        3  1925000        1]mulr 5 4 2     set reg 2 to multiply reg 4 and reg 5 
15400014 eqrr [       0 10551343        0        4  1925000        1]eqrr 2 1 2     if reg 2 = reg 1 set 2 to 1 else set 2 to 0
15400015 addr [       0 10551343        0        5  1925000        1]addr 2 3 3     add reg 2 and 3 and set to 3 ---> 0+5 no change
15400016 addi [       0 10551343        0        7  1925000        1]addi 3 1 3     add reg 3 and value 1 save in 3 ---> ip increment
15400017 addi [       0 10551343        0        8  1925001        1]addi 4 1 4     DONE add reg 4 and 1 save in 4 --> increment 4 1
15400018 gtrr [       0 10551343        0        9  1925001        1]gtrr 4 1 2     reg 2 to 1 if register 4 is greater than register 1
15400019 addr [       0 10551343        0       10  1925001        1]addr 3 2 3     reg 3 to reg 2+reg3
11244 gtrr                               [1, 10551343, 0, 9, 1404, 2]





def addr(reg,ins): #
    #(add register) stores into register C the result of adding register A and register B.
    result = reg[ins[1]]+reg[ins[2]]
    reg[ins[3]]=result
    return reg

def addi(reg,ins):#
    #addi (add immediate) stores into register C the result of adding register A and value B.

    reg[ins[3]]=reg[ins[1]]+ins[2]
    return reg


def mulr(reg,ins):#
    #mulr (multiply register) stores into register C the result of multiplying register A and register B.
    #set_trace()
    reg[ins[3]]=reg[ins[1]]*reg[ins[2]]
    return reg


def muli(reg,ins):#
    #muli (multiply immediate) stores into register C the result of multiplying register A and value B.
 
    reg[ins[3]]=reg[ins[1]]*ins[2]
    return reg



def banr(reg,ins):#
    #banr (bitwise AND register) stores into register C the result of the bitwise AND of register A and register B.

    reg[ins[3]]=reg[ins[1]]&reg[ins[2]]
    return reg



def bani(reg,ins):#
    #bani (bitwise AND immediate) stores into register C the result of the bitwise AND of register A and value B.
 
    reg[ins[3]]=reg[ins[1]]&ins[2]
    return reg



def borr(reg,ins):#
    #borr (bitwise OR register) stores into register C the result of the bitwise OR of register A and register B.

    reg[ins[3]]=reg[ins[1]]|reg[ins[2]]
    return reg



def bori(reg,ins):#
    #bori (bitwise OR immediate) stores into register C the result of the bitwise OR of register A and value B.
  
    reg[ins[3]]=reg[ins[1]]|ins[2]

    return reg



def setr(reg,ins):#
    #setr (set register) copies the contents of register A into register C. (Input B is ignored.)
    
    reg[ins[3]]=reg[ins[1]]
    return reg


def seti(reg,ins):#
    #seti (set immediate) stores value A into register C. (Input B is ignored.)
  
    reg[ins[3]]=ins[1]
    return reg



def gtir(reg,ins):#
    #gtir (greater-than immediate/register) sets register C to 1 if value A is greater than register B. Otherwise, register C is set to 0.
    if ins[1]>reg[ins[2]]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg



def gtri(reg,ins):#
    #gtri (greater-than register/immediate) sets register C to 1 if register A is greater than value B. Otherwise, register C is set to 0.
    if reg[ins[1]]>ins[2]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg





def gtrr(reg,ins):#
    #gtrr (greater-than register/register) sets register C to 1 if register A is greater than register B. Otherwise, register C is set to 0.
    if reg[ins[1]]>reg[ins[2]]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg




def eqir(reg,ins):#
    #eqir (equal immediate/register) sets register C to 1 if value A is equal to register B. Otherwise, register C is set to 0.

    if ins[1]==reg[ins[2]]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg




def eqri(reg,ins):#
    #qri (equal register/immediate) sets register C to 1 if register A is equal to value B. Otherwise, register C is set to 0.

    if reg[ins[1]]==ins[2]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg




def eqrr(reg,ins):
    #eqrr (equal register/register) sets register C to 1 if register A is equal to register B. Otherwise, register C is set to 0.
    if reg[ins[1]]==reg[ins[2]]:
        reg[ins[3]]=1
    else:
        reg[ins[3]]=0        
    return reg



In [70]:

instructions=[]
functions =[]
for i,line in enumerate(lines):
    newline =[0]
    for j,x in enumerate(line.split(' ')):
        print (j,x)
        if j>0:
            newline.append(int(x))
        else:
            functions.append(x)
    instructions.append (newline)
instructions = np.array(instructions)
instructions

0 addi
1 3
2 16
3 3
0 seti
1 1
2 8
3 5
0 seti
1 1
2 0
3 4
0 mulr
1 5
2 4
3 2
0 eqrr
1 2
2 1
3 2
0 addr
1 2
2 3
3 3
0 addi
1 3
2 1
3 3
0 addr
1 5
2 0
3 0
0 addi
1 4
2 1
3 4
0 gtrr
1 4
2 1
3 2
0 addr
1 3
2 2
3 3
0 seti
1 2
2 3
3 3
0 addi
1 5
2 1
3 5
0 gtrr
1 5
2 1
3 2
0 addr
1 2
2 3
3 3
0 seti
1 1
2 4
3 3
0 mulr
1 3
2 3
3 3
0 addi
1 1
2 2
3 1
0 mulr
1 1
2 1
3 1
0 mulr
1 3
2 1
3 1
0 muli
1 1
2 11
3 1
0 addi
1 2
2 4
3 2
0 mulr
1 2
2 3
3 2
0 addi
1 2
2 19
3 2
0 addr
1 1
2 2
3 1
0 addr
1 3
2 0
3 3
0 seti
1 0
2 7
3 3
0 setr
1 3
2 2
3 2
0 mulr
1 2
2 3
3 2
0 addr
1 3
2 2
3 2
0 mulr
1 3
2 2
3 2
0 muli
1 2
2 14
3 2
0 mulr
1 2
2 3
3 2
0 addr
1 1
2 2
3 1
0 seti
1 0
2 1
3 0
0 seti
1 0
2 5
3 3


array([[ 0,  3, 16,  3],
       [ 0,  1,  8,  5],
       [ 0,  1,  0,  4],
       [ 0,  5,  4,  2],
       [ 0,  2,  1,  2],
       [ 0,  2,  3,  3],
       [ 0,  3,  1,  3],
       [ 0,  5,  0,  0],
       [ 0,  4,  1,  4],
       [ 0,  4,  1,  2],
       [ 0,  3,  2,  3],
       [ 0,  2,  3,  3],
       [ 0,  5,  1,  5],
       [ 0,  5,  1,  2],
       [ 0,  2,  3,  3],
       [ 0,  1,  4,  3],
       [ 0,  3,  3,  3],
       [ 0,  1,  2,  1],
       [ 0,  1,  1,  1],
       [ 0,  3,  1,  1],
       [ 0,  1, 11,  1],
       [ 0,  2,  4,  2],
       [ 0,  2,  3,  2],
       [ 0,  2, 19,  2],
       [ 0,  1,  2,  1],
       [ 0,  3,  0,  3],
       [ 0,  0,  7,  3],
       [ 0,  3,  2,  2],
       [ 0,  2,  3,  2],
       [ 0,  3,  2,  2],
       [ 0,  3,  2,  2],
       [ 0,  2, 14,  2],
       [ 0,  2,  3,  2],
       [ 0,  1,  2,  1],
       [ 0,  0,  1,  0],
       [ 0,  0,  5,  3]])

In [125]:
ip = 3
before = np.zeros(shape=6)
before = before.astype(int)
before[ip]+=-1
#before = np.array([1, 943,   0,   6, 660,  941])
before = np.array([  1, 943,   0,  10, 382,  12])
#before[0]=1
#before=np.array([0,10551343,0,8,10551342,1])
#before =np.array([1, 10551343, 0, 8, 10551342, 2])
#before =np.array([1, 10551343, 0, 8, 10551342, 3])
#before =np.array([1, 10551343, 0, 8, 10551342, 4])
#before =np.array([1, 10551343, 0, 8, 0, 10551303])
#before = np.array([1, 10551343, 0, 8, 0, 10551342])
#before = np.array([10551344, 10551343, 0, 8, 10551342, 10551343])

#before = before.astype(np.int64)
for i in range(100000000):
    
    before[ip]+=1
    if before[ip]>=len(instructions):
        print (before)
        sys.exit(0)
    else:
    
        print (before,i,functions[before[ip]],eval(functions[before[ip]])(before.copy(),instructions[before[ip]]))
        before = eval(functions[before[ip]])(before.copy(),instructions[before[ip]])

[  1 943   0  11 382  12] 0 seti [  1 943   0   2 382  12]
[  1 943   0   3 382  12] 1 mulr [   1  943 4584    3  382   12]
[   1  943 4584    4  382   12] 2 eqrr [  1 943   0   4 382  12]
[  1 943   0   5 382  12] 3 addr [  1 943   0   5 382  12]
[  1 943   0   6 382  12] 4 addi [  1 943   0   7 382  12]
[  1 943   0   8 382  12] 5 addi [  1 943   0   8 383  12]
[  1 943   0   9 383  12] 6 gtrr [  1 943   0   9 383  12]
[  1 943   0  10 383  12] 7 addr [  1 943   0  10 383  12]
[  1 943   0  11 383  12] 8 seti [  1 943   0   2 383  12]
[  1 943   0   3 383  12] 9 mulr [   1  943 4596    3  383   12]
[   1  943 4596    4  383   12] 10 eqrr [  1 943   0   4 383  12]
[  1 943   0   5 383  12] 11 addr [  1 943   0   5 383  12]
[  1 943   0   6 383  12] 12 addi [  1 943   0   7 383  12]
[  1 943   0   8 383  12] 13 addi [  1 943   0   8 384  12]
[  1 943   0   9 384  12] 14 gtrr [  1 943   0   9 384  12]
[  1 943   0  10 384  12] 15 addr [  1 943   0  10 384  12]
[  1 943   0  11 384  12] 

KeyboardInterrupt: 

In [83]:
np.unique(functions)
before =np.array([1, 10551343, 0, 8, 10551342, 3])

array(['addi', 'addr', 'eqrr', 'gtrr', 'muli', 'mulr', 'seti', 'setr'],
      dtype='<U4')

In [80]:
10551343


7117776

In [ ]:
10551344 too low
10551343        
21102687too high
10551344

In [132]:
total =[]
for x in range (1,10551344):
    if 10551343%x==0: total.append(x)

In [129]:
1+23+41+943

1008

In [133]:
sum(total) #theanswer

11534976